version: '3.2'

services:
  webapi:
    build: .
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - ./bucket:/webapi/bucket
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=storage
      - DATABASE_PASSWORD=abcdefg
      - DATABASE_NAME=backend-project-0


  database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=backend-project-0
      - MYSQL_USER=storage
      - MYSQL_PASSWORD=abcdefg
    volumes:
      - ./mysql-data:/var/lib/mysql:rw